services:

# Prometheus # --------------------------------------------------------------------------------------------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "1000:1000"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    restart: unless-stopped
    mem_limit: 2g
    cpus: "1.5"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
    networks:
      - metrics_internal
      - db_internal

# PostgreSQL # --------------------------------------------------------------------------------------------------------------
  postgres:
    image: pgvector/pgvector:pg18
    container_name: postgres
    restart: unless-stopped
    mem_limit: 6g
    cpus: "4.0"
    user: 1000:1000
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./postgres:/var/lib/postgresql
    ports:
      - "5432:5432"
    networks:
      - db_internal

networks:
  metrics_internal:
    external: true
  db_internal:
    external: true
  proxy_public:
    external: true
